@startuml
skinparam conditionStyle inside
skinparam ActivityBackgroundColor #FEFECE
skinparam ActivityBorderColor #A80036

start
:Host truy cập Quản lý tin đăng;
:Hiển thị danh sách bài đăng;

if (Host chọn thao tác gì?) then (Thêm tin mới)
    :Hệ thống tải Form trống;
    :Host nhập thông tin (Tiêu đề, Giá, Loại BĐS...);
    :Upload Ảnh/Video (Tối đa 10 ảnh, 1 video);
    :Nhấn "Lưu và Đăng xuất bản";

    if (Dữ liệu & File hợp lệ?) then (Không)
        :Báo lỗi đỏ tại trường tương ứng\n(Thiếu info hoặc File > 10MB);
        stop
    else (Có)
        :Lưu Property mới vào DB (Status = PENDING);
    endif

elseif (Chọn thao tác?) then (Cập nhật)
    :Hệ thống tải dữ liệu cũ vào Form;
    :Host chỉnh sửa nội dung / thay đổi file;
    :Nhấn "Lưu và Đăng xuất bản";

    if (Dữ liệu & File hợp lệ?) then (Không)
        :Báo lỗi tại trường tương ứng;
        stop
    else (Có)
        :Cập nhật Property hiện tại;
        :Thiết lập Trạng thái = PENDING;
    endif

else (Xóa)
    :Host nhấn "Xóa";
    :Hiển thị Popup xác nhận;

    if (Xác nhận?) then (Hủy)
        stop
    else (Đồng ý)
        :Cập nhật Trạng thái = DELETED;
    endif
endif

:Hiển thị thông báo thành công (Success);
:Điều hướng Host về màn hình Danh sách;
stop

@enduml