@startuml
skinparam conditionStyle inside
skinparam ActivityBackgroundColor #FEFECE
skinparam ActivityBorderColor #A80036

start
:Người dùng truy cập trang xác thực;

if (Lựa chọn chức năng?) then (Đăng nhập)
    :Hệ thống hiển thị form Đăng nhập;
    :Người dùng nhập Email, Mật khẩu;

    if (Frontend validation sai?) then (Có)
        :Hiển thị lỗi validate;
        stop
    else (Không)
        :Gửi POST /users/login;
        :Tim user theo email;

        if (Không tìm thấy user?) then (Có)
            :Trả lời "Tài khoản hoặc mật khẩu không chính xác";
            stop
        else (Không)
            :Đối chiếu passwordHash;

            if (Password sai?) then (Có)
                :Trả lời "Tài khoản hoặc mật khẩu không chính xác";
                stop
            else (Không)
                if (Status = LOCKED?) then (Có)
                    :Trả lời "Tài khoản của bạn đã bị khóa. Vui lòng liên hệ Admin để hỗ trợ.";
                    stop
                else (Không)
                     :Cập nhật last_login_at;
                     :Tạo AuthSession;
                     :Sinh Refresh Token và lưu DB;
                     :Sinh Access Token;
                     :Trả về accessToken, refreshToken, user;
                     :Frontend lưu token và chuyển hướng đến dashboard;
                     stop
                endif
            endif
        endif
    endif
else (Đăng ký Host)
    :Hệ thống hiển thị form Đăng ký Host;
    :Người dùng nhập Họ tên, Email, Số điện thoại,\nMật khẩu, Xác nhận mật khẩu;

    if (Frontend validation sai?) then (Có)
        :Hiển thị lỗi validate;
        stop
    else (Không)
        :Gửi POST /users/register;

        if (Password va Confirm không khớp?) then (Có)
            :Trả lời "Xác nhận mật khẩu không khớp";
            stop
        else (Không)
            :Kiểm tra email đã tồn tại;

            if (Email đã tồn tại?) then (Có)
                :Trả lời "Email này đã được đăng ký";
                stop
            else (Khong)
                :Kiểm tra số điện thoại đã tồn tại;

                if (Số điện thoại đã tồn tại?) then (Có)
                    :Tra loi "Số điện thoại này đã được đăng ký";
                    stop
                else (Khong)
                    :Mã hóa mật khẩu bằng BCrypt;
                    :Gán role HOST;
                    :Lưu user với status = PENDING;
                    :Gửi thông báo có user mới đăng ký cho Admin;
                    :Trả thông báo đăng ký thành công;
                    :Chuyển hướng đến trang đăng nhập;
                    stop
                endif
            endif
        endif
    endif
endif

@enduml
